name: Main Check & Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Code Base Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true

      - name: Run the default task
        run: bundle exec rake
